"""Write generated rows as PostgreSQL `COPY` input, and the script that loads them.

Plan H4 loads with `COPY` rather than through the API, which is orders of magnitude faster and the
only way millions of rows arrive in reasonable time. Three things that costs us, all handled here.

**The column list belongs to the database, not to this file.** Migrations accumulate, so a hardcoded
list would rot and produce a `COPY` that either fails or -- far worse -- shifts every value one
column to the left and loads silently. The caller supplies the column list, read from
`information_schema.columns` on the target, and rows are projected onto it. A row key that is not a
column is an error rather than a value quietly dropped.

**Explicit ids leave the sequences behind.** The generator assigns its own ids so it can wire foreign
keys without round-tripping the database. `COPY` does not advance a serial's sequence, so the first
application insert after a load collides on the primary key. `load_script` emits a `setval` per table
to close that.

**TEXT format has its own escaping.** A tab or newline inside a value ends the field or the row, so
backslash, tab, newline and carriage return are escaped, and NULL is `\\N` -- which is why the
backslash has to be escaped first.

**Load order is load-bearing.** None of Avni's foreign keys are declared `DEFERRABLE`, so
`SET CONSTRAINTS ALL DEFERRED` achieves nothing and a child row loaded before its parent fails on
the spot. `LOAD_ORDER` is the only thing preventing that.
"""
from __future__ import annotations

import json
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path
from typing import Iterable, Mapping, Sequence

NULL = r"\N"

# Order matters: a row cannot reference a table loaded after it.
LOAD_ORDER = (
    "address_level",
    "catchment",
    "catchment_address_mapping",
    "users",
    "individual",
    "program_enrolment",
    "program_encounter",
    "encounter",
)


def escape(value: str) -> str:
    """Escape one value for `COPY ... FORMAT text`. Backslash first, or the rest double-escape."""
    return (value.replace("\\", "\\\\")
                 .replace("\t", "\\t")
                 .replace("\n", "\\n")
                 .replace("\r", "\\r"))


def render(value) -> str:
    """One Python value as its `COPY` text representation."""
    if value is None:
        return NULL
    if isinstance(value, bool):
        return "t" if value else "f"
    if isinstance(value, (int, Decimal)):
        return str(value)
    if isinstance(value, float):
        # repr keeps full precision; str() rounds in older versions.
        return repr(value)
    if isinstance(value, datetime):
        return escape(value.isoformat(sep=" "))
    if isinstance(value, date):
        return value.isoformat()
    if isinstance(value, (dict, list)):
        # jsonb. separators drop the spaces json.dumps adds by default, which is a real saving
        # across millions of observation maps.
        return escape(json.dumps(value, separators=(",", ":"), default=str))
    return escape(str(value))


def project(row: Mapping, columns: Sequence[str], *, table: str = "") -> list[str]:
    """Lay a row out in the target's column order, refusing keys that are not columns."""
    unknown = set(row) - set(columns)
    if unknown:
        where = f" for {table}" if table else ""
        raise KeyError(
            f"row keys{where} are not columns in the target: {sorted(unknown)}. "
            f"Either the schema moved or a name is misspelt -- both would otherwise load silently."
        )
    return [render(row.get(c)) for c in columns]


def write_table(path: Path, rows: Iterable[Mapping], columns: Sequence[str],
                *, table: str = "") -> int:
    """Write one table's `COPY` file. Returns the row count."""
    path.parent.mkdir(parents=True, exist_ok=True)
    n = 0
    with path.open("w", encoding="utf-8", newline="\n") as fh:
        for row in rows:
            fh.write("\t".join(project(row, columns, table=table or path.stem)))
            fh.write("\n")
            n += 1
    return n


def load_script(tables: Mapping[str, Sequence[str]], *, directory: str = ".",
                serial_tables: Iterable[str] | None = None,
                build_indexes_after: bool = True) -> str:
    """The SQL that loads the written files, in dependency order.

    Index creation is left to the caller's own DDL: H4 builds indexes after the load, and G4
    requires them to match production's definitions exactly, so they are not invented here.
    """
    ordered = [t for t in LOAD_ORDER if t in tables] + \
              [t for t in tables if t not in LOAD_ORDER]
    serials = set(serial_tables if serial_tables is not None else ordered)

    out = [
        "-- Generated by tools/data-generator. Loads one dataset.",
        "-- Run with psql:  psql -d <db> -v ON_ERROR_STOP=1 -f load.sql",
        "--",
        "-- \\copy, not COPY: server-side COPY FROM reads a path on the database host and needs",
        "-- superuser or pg_read_server_files. \\copy streams the file from wherever psql runs.",
        "--",
        "-- Load order is load-bearing. None of Avni's foreign keys are declared DEFERRABLE, so",
        "-- SET CONSTRAINTS ALL DEFERRED would do nothing here and a child row loaded before its",
        "-- parent fails immediately.",
        "BEGIN;",
        "",
    ]
    for t in ordered:
        cols = ", ".join(tables[t])
        out += [f"\\echo loading {t}",
                f"\\copy {t} ({cols}) FROM '{directory}/{t}.tsv' WITH (FORMAT text)",
                ""]

    if serials:
        out += ["-- COPY does not advance a sequence, so the first application insert after this",
                "-- load would collide on the primary key.", ""]
        for t in ordered:
            if t in serials:
                out.append(
                    f"SELECT setval(pg_get_serial_sequence('{t}', 'id'), "
                    f"COALESCE((SELECT MAX(id) FROM {t}), 1));")
        out.append("")

    out += ["COMMIT;", ""]
    if build_indexes_after:
        out += ["-- Build indexes and refresh statistics after the load, not before (H4).",
                "-- The index definitions are production's own and belong with the schema.",
                "ANALYZE;", ""]
    return "\n".join(out)
